### ISSUE TITLE
Support Request: Huion Kamvas pro 13 working by itself, not with otd (another github user who can't read FAQ)

### ISSUE THREAD

**Issue by danbulant** [OpenTabletDriver/OpenTabletDriver#1555]
I'm trying to change area on my Huion Kamvas pro 13 tablet. By itself, the tablet already works, but doesn't work with another monitor at once (cursor is mapped the wrong way). Buttons aren't working.
When I install OTD (using AUR 0.5.3.3), at first (before reboot), it doesn't detect the tablet. Diagnostic information shows Failed to open device streams. I looked into 'generate new config' and the tablet was found there (twice?) with correct vendor and product ID. Using `uclogic-probe`, I found out that the firmware version (string 201) does match what's in the kamvas pro 13 configuration (HUION_M182_190218).  After I run the reload udev rules, it still didn't detect it, so I rebooted.
After reboot, the laptop doesn't work at all (screen does work, but no pen input). After running export diagnostics, the application crashes.

<details>
  <summary>Crash stack trace</summary>
  
  ```
 Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
Newtonsoft.Json.JsonSerializationException: Error getting value from 'MaxInputReportLength' on 'HidSharp.Platform.Linux.LinuxHidDevice'.
 ---> System.ArgumentOutOfRangeException: Value range is [0, 15]. (Parameter 'value')
   at HidSharp.Reports.Units.Unit.DecodeExponent(UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseMainData(MainItemTag tag, UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseMain(MainItemTag tag, UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseEncodedItem(EncodedItem item)
   at HidSharp.Reports.ReportDescriptor.ParseEncodedItems(IEnumerable`1 items)
   at HidSharp.Reports.ReportDescriptor.ParseRawReportDescriptor(Byte[] buffer)
   at HidSharp.Reports.ReportDescriptor..ctor(Byte[] buffer)
   at HidSharp.Platform.Linux.LinuxHidDevice.TryParseReportDescriptor(ReportDescriptor& parser, Byte[]& reportDescriptor)
   at HidSharp.Platform.Linux.LinuxHidDevice.RequiresGetInfo()
   at HidSharp.Platform.Linux.LinuxHidDevice.GetMaxInputReportLength()
   at HidSharp.HidDevice.get_MaxInputReportLength()
   at lambda_method98(Closure , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)
   at OpenTabletDriver.Desktop.Diagnostics.DiagnosticInfo.ToString() in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.Desktop/Diagnostics/DiagnosticInfo.cs:line 40
   at OpenTabletDriver.UX.MainForm.ExportDiagnostics() in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/MainForm.cs:line 578
   at OpenTabletDriver.UX.MainForm.<ConstructMenu>b__11_14(Object sender, EventArgs e) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/MainForm.cs:line 312
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Eto.GtkSharp.Forms.GtkSynchronizationContext.<>c__DisplayClass0_0.<Post>b__0()
   at GLib.Idle.IdleProxy.Handler()
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.Idle.IdleProxy.Handler()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/App.cs:line 49
   at OpenTabletDriver.UX.Gtk.Program.Main(String[] args) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX.Gtk/Program.cs:line 10
```
</details>
<details>
 <summary>Saving configuration crashes</summary>

```
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UnauthorizedAccessException: Access to the path '/usr/share/OpenTabletDriver/Configurations/Gaomon/1060 Pro.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at OpenTabletDriver.Desktop.Serialization.Serialize(FileInfo file, Object value) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.Desktop/Serialization.cs:line 36
   at OpenTabletDriver.UX.Windows.Configurations.ConfigurationEditor.WriteConfigurations(IEnumerable`1 configs, DirectoryInfo dir) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/Windows/Configurations/ConfigurationEditor.cs:line 157
   at OpenTabletDriver.UX.Windows.Configurations.ConfigurationEditor.SaveConfigurationsDialog(DirectoryInfo dir) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/Windows/Configurations/ConfigurationEditor.cs:line 204
   at OpenTabletDriver.UX.Windows.Configurations.ConfigurationEditor.<.ctor>b__0_2(Object sender, EventArgs e) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/Windows/Configurations/ConfigurationEditor.cs:line 47
   at Eto.Forms.Command.OnExecuted(EventArgs e)
   at Eto.Forms.Command.Execute()
   at Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
   at Eto.PropertyStore.CommandWrapper.Command_Execute(Object sender, EventArgs e)
   at Eto.Forms.MenuItem.OnClick(EventArgs e)
   at Eto.Forms.MenuItem.Callback.OnClick(MenuItem widget, EventArgs e)
   at Eto.GtkSharp.Forms.Menu.ButtonMenuItemHandler`2.ButtonMenuItemConnector.HandleActivated(Object sender, EventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX/App.cs:line 49
   at OpenTabletDriver.UX.Gtk.Program.Main(String[] args) in /var/tmp/pamac-build-dan/opentabletdriver/src/OpenTabletDriver-0.5.3.3/OpenTabletDriver.UX.Gtk/Program.cs:line 10
```
</details>

Event after I did what was in the FAQ about udev rules (using latest artifact from GH actions, as of sending this SR), and run the udev reload (both before and after adding that file), I'm still getting the same issue in logs.

I'm on Manjaro (kernel 5.10.70-1-MANJARO), using 0.5.3.3 from AUR (the non-git version as it seems the normal one is newer than the -git version? At least based on the version number).

**Comment by gonX** [comment]
From what I can establish the issue was the config was using an incorrect parser (`TabletReportParser` -> `UCLogicReportParser` fixes it) for the `110` ProductID.

I'll open a PR to fix this since its likely just an oversight given ProductID 109 (1 less) uses the correct parser. Please correct me if I'm wrong on any of this.

Closing as it seems your issue was resolved.
