### ISSUE TITLE
Command setoutputmode not working

### ISSUE THREAD

**Issue by d3xMachina** [OpenTabletDriver/OpenTabletDriver#1952]
## Description
When I try the command (on windows) :
OpenTabletDriver.Console.exe setoutputmode "Gaomon S620" "Relative Mode"
I get : 
> Unhandled exception: StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
>    at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
>    at OpenTabletDriver.Console.Program.ApplySettings(Settings settings)
>    at OpenTabletDriver.Console.Program.ModifySettings(Action`1 func)
>    at OpenTabletDriver.Console.Program.ModifyProfile(String profileName, Action`1 func)
>    at OpenTabletDriver.Console.Program.SetOutputMode(String tablet, String mode)
>    at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
>    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
>    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
> RPC server exception:
> System.NullReferenceException: Object reference not set to an instance of an object.
>       at System.Object.GetType()
>       at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.TriggerEventMethods(Object obj, TabletReference tabletReference)
>       at OpenTabletDriver.Desktop.Reflection.PluginSettingStore.Construct[T](TabletReference tabletReference, Boolean trigger)
>       at OpenTabletDriver.Daemon.DriverDaemon.SetSettings(Settings settings)

But the following command is working properly : 
OpenTabletDriver.Console.exe getoutputmode "Gaomon S620"

## System Information:
| Operating System         | Windows
| OpenTabletDriver Version | v0.6.0.1
| Tablet                   | Gaomon S620

**Comment by gonX** [comment]
Fixed in #4148
