### ISSUE TITLE
h420x not detected even with custom config

### ISSUE THREAD

**Issue by HoosierTransfer** [OpenTabletDriver/OpenTabletDriver#1990]
I found a config for the h420x and it detects the tablet but errors out

the logs are
Application: OpenTabletDriver.UX.Wpf.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTabletDriver.Desktop.Profiles.AreaSettings.GetDefaults(DigitizerSpecifications digitizer)
   at OpenTabletDriver.Desktop.Profiles.AbsoluteModeSettings.GetDefaults(DigitizerSpecifications digitizer)
   at OpenTabletDriver.Desktop.Profiles.Profile.GetDefaults(TabletReference tablet)
   at OpenTabletDriver.UX.Controls.TabletSwitcherPanel.TabletSwitcher.HandleTabletsChanged(Object sender, IList`1 tablets)
   at OpenTabletDriver.UX.Controls.TabletSwitcherPanel.TabletSwitcher.OnProfilesChanged()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Eto.Wpf.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args)
   at OpenTabletDriver.UX.Wpf.Program.Main(String[] args)

and

Faulting application name: OpenTabletDriver.UX.Wpf.exe, version: 0.6.0.2, time stamp: 0x61954b73
Faulting module name: KERNELBASE.dll, version: 10.0.22000.434, time stamp: 0x72a6f702
Exception code: 0xe0434352
Fault offset: 0x000000000004478c
Faulting process id: 0x3920
Faulting application start time: 0x01d80e127c0dc191
Faulting application path: C:\Users\Luke\OpenTabletDriver.win-x64 (1)\OpenTabletDriver.UX.Wpf.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: cfe6c04b-8fb4-4cd0-9150-b08ea45f49ae
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jamesbt365** [comment]
Are you sure this isn't invalid settings and could you get a crash from the daemon?

**Comment by jamesbt365** [comment]
Nevermind it is a migration issue, remove the settings file from %localappdata%\OpenTabletDriver
