### ISSUE TITLE
Add Wacom CTL-6100WL Bluetooth support!

### ISSUE THREAD

**Issue by ShadowOfPripyat** [OpenTabletDriver/OpenTabletDriver#2118]
## Description

Hello, i bought the **Wacom Intuos M** (**Bluetooth** model) a few days ago and i found out this page from the game "**osu!**", i followed the steps to install your drivers but Bluetooth doesn't work.

I think that this is an important feature because this tablet is a bit expensive and its main feature its being **wireless**

![image](https://user-images.githubusercontent.com/73404930/158013546-8769dbe7-1b09-4b59-b839-29cf24239ab8.png)
![image](https://user-images.githubusercontent.com/73404930/158013607-e4b09062-e930-40ca-9098-607985cf69d8.png)

Thank You :D

**Comment by IllustratedMan-code** [comment]
This is currently impossible to implement as long as opentabletdriver is dependent on HIDSharp, see #2628

**Comment by ShadowDeveloper** [comment]
It is a bluetooth tablet. No support

**Comment by ShadowOfPripyat** [comment]
The smaller model of this tablet is supported with bluetooth. why this bigger model isn't?

**Comment by IllustratedMan-code** [comment]
Bluetooth tablets in general are not supported, see

https://github.com/OpenTabletDriver/OpenTabletDriver/issues/3047

**Comment by gonX** [comment]
This needs additional diagnostics files from users of this tablet to have any chance of being looked at (and potentially a USB String Dump of the connected receiver)

From what I can remember, this is caused by the Bluetooth modem looking the same regardless of tablet. Perhaps a project maintainer needs to open an issue describing this issue in general so that we can mark that issue as blocking this.

Obviously, the Wacom driver seems to be able tell the difference, so there should be a way for us to do this as well, even if it does require changes in HIDSharp.

**Comment by Dutchs** [comment]
The ProductID for this device is 968, this appears to be working from some initial testing with #4672 
`..\Configurations\Wacom\CTL-6100WL.json`
```json
{
   "VendorID": 1386,
   "ProductID": 968,
   "InputReportLength": 361,
   "ReportParser": "OpenTabletDriver.Configurations.Parsers.Wacom.IntuosV2.IntuosV2BluetoothReportParser"
}
```

And in case it's helpful, here are the diagnostics:
```json
{
  "DevicePath": "\\\\?\\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0001056a_pid&03c8#8&35fa69ea&3&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}",
  "Manufacturer": "Wacom Co.,Ltd.",
  "ProductName": "Wacom Intuos PBM",
  "SerialNumber": "",
  "FriendlyName": "Wacom Intuos PBM",
  "VendorID": 1386,
  "ProductID": 968,
  "InputReportLength": 361,
  "OutputReportLength": 361,
  "FeatureReportLength": 361,
  "CanOpen": true,
  "DeviceAttributes": {
    "HID_REPORTS": "81:FF0D:0001, 80:FF0D:0001"
  }
}
```


After some further testing, IntuosV2BluetoothReport and IntuosV2BluetoothReportParser would need a few changes for this to function perfectly with the CTL-6100WL, specifically to support the 4 Aux buttons this tablet has:

<img width="394" height="669" alt="Image" src="https://github.com/user-attachments/assets/8402783b-af4a-4a7b-9b22-8965e19ff012" />

From left to right, these bits relate to buttons 4, 3, 2 and 1.
0 = released, 1 = held down

For pen near/far proximity detection:

<img width="272" height="666" alt="Image" src="https://github.com/user-attachments/assets/4fdc53f7-d104-4599-84df-c922d6cabb21" />

E1 = tip makes contact with tablet
E0 = tip hovers close to tablet <1cm
C0 = tip hovers further from table >1cm

**Comment by hey2022** [comment]
I managed to get aux buttons working on linux, but the code I wrote probably ins't that great (I don't really know anything about tablet drivers):
1. Build HIDSharpCore with [#28](https://github.com/OpenTabletDriver/HIDSharpCore/pull/28) and the fix mentioned in #4672 (https://github.com/hey2022/HIDSharpCore/tree/basic-bluetooth)
2. Build OTD with #4672 and the config for CTL-6100WL mentioned by @Dutchs with another patch for aux buttons (https://github.com/hey2022/OpenTabletDriver/tree/bluetooth-ctl6100wl) and replace the `HidSharpCore.dll` with the previously patched build.
3. I also had to add udev rules for bluetooth permissions: `SUBSYSTEM=="hidraw", MODE="0666", TAG+="uaccess", TAG+="udev-acl"` or else there would be an error:
	```
	[DeviceUnauthorizedAccessException:Debug]	Not permitted to open HID class device at /dev/hidraw1.
	   at HidSharp.Platform.Linux.LinuxHidStream.DeviceHandleFromPath(String path, HidDevice hidDevice, oflag oflag)
	   at HidSharp.Platform.Linux.LinuxHidDevice.TryParseReportDescriptor(ReportDescriptor& parser, Byte[]& reportDescriptor)
	   at HidSharp.Platform.Linux.LinuxHidDevice.RequiresGetInfo()
	   at HidSharp.Platform.Linux.LinuxHidDevice.GetMaxInputReportLength()
	   at OpenTabletDriver.Devices.HidSharpBackend.HidSharpEndpoint.<>c.<get_InputReportLength>b__7_0(HidDevice d) in /build/source/OpenTabletDriver/Devices/HidSharpBackend/HidSharpEndpoint.cs:line 25
	   at OpenTabletDriver.Extensions.TryGet[TSource,TValue](TSource source, Func`2 predicate, TValue& value) in /build/source/OpenTabletDriver/Extensions.cs:line 12
	```
	I tried making the udev rule more specific, but for some reason it just wont match correctly.

For people on NixOS you can refer to my commit that got everything working (https://github.com/hey2022/dotfiles/commit/c34e66f3f7bcf40261c24ba15f7ec809955c947e)

**Comment by Tsuyumi25** [comment]
@Dutchs @hey2022, thanks for the CTL-6100WL Bluetooth investigation and testing in this thread; #4672 now includes the device configuration, four ExpressKeys, report-state handling, and the generated Linux hidraw permission rule. A fresh PID `0x03C8` Tablet Debugger recording covering pen input, proximity exit/re-entry, and all four ExpressKeys would be welcome when convenient.

For an additional Linux integration check, please use https://github.com/OpenTabletDriver/HIDSharpCore/pull/31, disable any custom broad hidraw rule such as `MODE="0666"`, install the rules generated by #4672, and reconnect the tablet before launching OTD. Confirming that OTD detects it as a regular user would verify the Linux permission path too. The recording alone is sufficient for the CTL-6100WL parser behavior.
