### ISSUE TITLE
Unhandled null reference when detecting tablets (osu-framework)

### ISSUE THREAD

**Issue by InfinityGhost** [OpenTabletDriver/OpenTabletDriver#2179]
## Description

Unhandled null reference when detecting tablets (osu-framework)

See https://github.com/ppy/osu/issues/17711#issuecomment-1092552221

```cs
2022-04-07 13:11:40 [verbose]: Detect: Searching for tablets...
2022-04-07 13:11:40 [verbose]: Detect: Found tablet 'Wacom CTL-472'
2022-04-07 13:11:45 [error]: An unobserved error has occurred.
2022-04-07 13:11:45 [error]: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
2022-04-07 13:11:45 [error]: ---> System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler.<>c__DisplayClass17_0.<Initialize>b__5(Object s, IEnumerable`1 e)
2022-04-07 13:11:45 [error]: at OpenTabletDriver.Driver.Detect()
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.TabletDriver.detectAsync(CancellationToken cancellationToken)
2022-04-07 13:11:45 [error]: --- End of inner exception stack trace ---
2022-04-07 13:11:45 [error]: An unobserved error has occurred. (inner)
2022-04-07 13:11:45 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler.<>c__DisplayClass17_0.<Initialize>b__5(Object s, IEnumerable`1 e)
2022-04-07 13:11:45 [error]: at OpenTabletDriver.Driver.Detect()
2022-04-07 13:11:45 [error]: at osu.Framework.Input.Handlers.Tablet.TabletDriver.detectAsync(CancellationToken cancellationToken)
2022-04-07 13:11:45 [verbose]: ⚠️ An unobserved error has occurred.
```

**Comment by X9VoiD** [comment]
Resolved by #2552
