### ISSUE TITLE
ArgumentOutOfRangeException: Value range is [0, 15]. (Parameter 'value')

### ISSUE THREAD

**Issue by nanashi-1** [OpenTabletDriver/OpenTabletDriver#2355]
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. Launch OpenTabletDriver

### Expected Behavior

Detect my tablet

### Observed Behavior

OpenTabletDriver says there's "No Tablet detected".

### Tablet Device

Gaomon S620

### Diagnostic Information

OS: Arch Linux nanashi-computer 5.18.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 15 Jul 2022 15:33:04 +0000 x86_64 GNU/Linux

```json

[Detect:Debug]	Searching for tablet 'Gaomon S620'
[ArgumentOutOfRangeException:Error]	Value range is [0, 15]. (Parameter 'value')
   at HidSharp.Reports.Units.Unit.DecodeExponent(UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseMainData(MainItemTag tag, UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseEncodedItem(EncodedItem item)
   at HidSharp.Reports.ReportDescriptor.ParseEncodedItems(IEnumerable`1 items)
   at HidSharp.Reports.ReportDescriptor.ParseRawReportDescriptor(Byte[] buffer)
   at HidSharp.Reports.ReportDescriptor..ctor(Byte[] buffer)
   at HidSharp.Platform.Linux.LinuxHidDevice.TryParseReportDescriptor(ReportDescriptor& parser, Byte[]& reportDescriptor)
   at HidSharp.Platform.Linux.LinuxHidDevice.RequiresGetInfo()
   at HidSharp.Platform.Linux.LinuxHidDevice.GetMaxInputReportLength()
   at OpenTabletDriver.Devices.HidSharpBackend.HidSharpEndpoint.<>c.<get_InputReportLength>b__7_0(HidDevice d)
   at OpenTabletDriver.Extensions.TryGet[TSource,TValue](TSource source, Func`2 predicate, TValue& value)
[Detect:Info]	No tablets were detected.
[IPC:Debug]	Connected to a client.
[Settings:Info]	Presets have been refreshed. Loaded 0 presets.

```

**Comment by jamesbt365** [comment]
Actually search for other issues instead of  clicking all the boxes without reading. Thank you.
