### ISSUE TITLE
Plugin manager throws an error when uninstalling and installing plugins

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#2406]
## Description

Upon installing or uninstalling any plugin through the plugin repo or local file the following error is thrown.

```
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Controls.ItemsControl.set_ItemsSource(IEnumerable value)
   at Eto.Wpf.Forms.Controls.ListBoxHandler.set_DataStore(IEnumerable`1 value)
   at Eto.Forms.ListControl.set_DataStore(IEnumerable`1 value)
   at OpenTabletDriver.UX.Controls.Editors.PluginSettingsPanel`1.Refresh() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Controls\Editors\PluginSettingsPanel.cs:line 57
   at OpenTabletDriver.UX.Controls.Editors.PluginSettingsPanel`1.<.ctor>b__7_0(Object _, PluginEventType _) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Controls\Editors\PluginSettingsPanel.cs:line 45
   at OpenTabletDriver.Desktop.Reflection.PluginManager.Unload() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Reflection\PluginManager.cs:line 113
   at OpenTabletDriver.Desktop.Reflection.PluginManager.Load() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Reflection\PluginManager.cs:line 98
   at OpenTabletDriver.UX.App.SynchronizePlugins(IDriverDaemon daemon) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\App.cs:line 205
```

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win10
| Software Version | [82b9c1f](https://github.com/OpenTabletDriver/OpenTabletDriver/commit/82b9c1f2131a4312cab456a3bc73b5d39a2113fb)

**Comment by gonX** [comment]
Indirectly fixed in #2772
