### ISSUE TITLE
Launching OTD with an out of date plugin in the plugins folder causes the UX to crash

### ISSUE THREAD

**Issue by Kuuuube** [OpenTabletDriver/OpenTabletDriver#2407]
## Description

In 0.6.0, out of date plugins would fail to load but not cause a crash. This behavior should be the same in 0.7.0. 

This is only caused when launching OTD with an out of date plugin already installed. It does not happen when installing an out of date plugin.

```
Application: OpenTabletDriver.UX.Wpf.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.<>c.<get_PluginTypes>b__22_0(Assembly asm) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.Desktop\Reflection\PluginManager.cs:line 58
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at OpenTabletDriver.UX.Controls.OutputModePicker.CreateDefaultDataStore() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Controls\OutputModePicker.cs:line 24
   at OpenTabletDriver.UX.Controls.OutputModePicker.<Refresh>b__3_0() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Controls\OutputModePicker.cs:line 29
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Eto.Wpf.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Start() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\App.cs:line 74
   at OpenTabletDriver.UX.Wpf.Program.Main(String[] args) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX.Wpf\Program.cs:line 8
System.IO.FileNotFoundException: Could not load file or assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'
```

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Win10
| Software Version | [82b9c1f](https://github.com/OpenTabletDriver/OpenTabletDriver/commit/82b9c1f2131a4312cab456a3bc73b5d39a2113fb)

**Comment by gonX** [comment]
Indirectly fixed in #2772 - master is deprecated, so closing as stale.
