### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by solonovamax** [OpenTabletDriver/OpenTabletDriver#2800]
### Steps to Reproduce

Launch open tablet driver

### Expected Behavior

Doesn't crash

### Observed Behavior

Crashes

### Tablet Device

XP-Pen Star G640 V2

### Diagnostic Information

```
[Detect:Debug]	Searching for tablet 'XP-Pen Star G960'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G960S Plus'
[Detect:Debug]	Searching for tablet 'XP-Pen Star G960S'
[Evdev:Debug]	Successfully initialized virtual pressure sensitive tablet. (code NONE)
[XP-Pen Star G640 V2:Info]	Output mode: Artist Mode
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTabletDriver.Daemon.DriverDaemon.SetAbsoluteModeSettings(InputDeviceTree dev, AbsoluteOutputMode absoluteMode, AbsoluteModeSettings settings)
   at OpenTabletDriver.Daemon.DriverDaemon.SetSettings(Settings settings)
   at OpenTabletDriver.Daemon.DriverDaemon.LoadUserSettings()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
/usr/bin/otd: line 13: 27563 Aborted                 (core dumped) dotnet ./OpenTabletDriver.Daemon.dll
```

perhaps this has something to do with reading the settings?
so, here's my settings:
```json
{
  "Revision": "0.7.0.0",
  "Profiles": [
    {
      "Tablet": "XP-Pen Star G640 V2",
      "OutputMode": {
        "Path": "OpenTabletDriver.Desktop.Output.LinuxArtistMode",
        "Settings": [
          {
            "Property": "Input",
            "Value": {
              "Rotation": 0.0,
              "Width": 160.0,
              "Height": 100.0,
              "XPosition": 80.0,
              "YPosition": 50.0
            }
          },
          {
            "Property": "Output",
            "Value": {
              "Width": 1920.0,
              "Height": 1080.0,
              "XPosition": 2880.0,
              "YPosition": 540.0
            }
          },
          {
            "Property": "LockAspectRatio",
            "Value": false
          },
          {
            "Property": "AreaClipping",
            "Value": false
          },
          {
            "Property": "AreaLimiting",
            "Value": false
          },
          {
            "Property": "LockToBounds",
            "Value": false
          }
        ],
        "Enable": true
      },
      "Filters": [
        {
          "Path": "Chatter_Exterminator.Chatter_Exterminator_Filter",
          "Settings": [
            {
              "Property": "AntichatterStrength",
              "Value": 2.0
            }
          ],
          "Enable": false
        },
        {
          "Path": "SinCursor.SinCursor",
          "Settings": [
            {
              "Property": "Amplitude",
              "Value": 10.0
            },
            {
              "Property": "ElasticAmp",
              "Value": true
            },
            {
              "Property": "Freq",
              "Value": 10.0
            },
            {
              "Property": "ElasticFreq",
              "Value": false
            }
          ],
          "Enable": false
        },
        {
          "Path": "HandSpeed.CustomFilter",
          "Settings": [
            {
              "Property": "SpeedFormat",
              "Value": "{0:N1}{1}/s"
            },
            {
              "Property": "DistanceFormat",
              "Value": "{0:N}{1}"
            },
            {
              "Property": "ShowMetres",
              "Value": false
            },
            {
              "Property": "SaveGlobalDistance",
              "Value": true
            },
            {
              "Property": "RollingWindow",
              "Value": 1000
            },
            {
              "Property": "RateLimit",
              "Value": 10
            },
            {
              "Property": "ClearInterval",
              "Value": 2000
            },
            {
              "Property": "ServerUri",
              "Value": "localhost:8073"
            },
            {
              "Property": "BackgroundColor",
              "Value": "#1C1B22"
            },
            {
              "Property": "TextColor",
              "Value": "#fff"
            },
            {
              "Property": "Outline",
              "Value": "1px solid #414141; outline-offset: -1px"
            },
            {
              "Property": "BorderRounding",
              "Value": "0.75rem"
            },
            {
              "Property": "FontFamily",
              "Value": "Inter"
            },
            {
              "Property": "FontWeight",
              "Value": "bold"
            },
            {
              "Property": "FontSize",
              "Value": "3rem"
            },
            {
              "Property": "Title",
              "Value": "Hand Speed"
            },
            {
              "Property": "Width",
              "Value": "20rem"
            },
            {
              "Property": "CustomDivStyle",
              "Value": ""
            },
            {
              "Property": "CustomTitleStyle",
              "Value": ""
            },
            {
              "Property": "CustomDistanceStyle",
              "Value": ""
            },
            {
              "Property": "CustomSpeedStyle",
              "Value": ""
            }
          ],
          "Enable": false
        },
        {
          "Path": "Pressure_Debounce.Pressure_Debounce",
          "Settings": [
            {
              "Property": "Debounce_timer",
              "Value": 30.0
            },
            {
              "Property": "Pressure_threshold",
              "Value": 1.0
            },
            {
              "Property": "Drop_excess",
              "Value": null
            },
            {
              "Property": "Disable_timer",
              "Value": null
            }
          ],
          "Enable": false
        },
        {
          "Path": "Tablet_Area_Randomizer.Tablet_Area_Randomizer",
          "Settings": [
            {
              "Property": "Time_interval_min",
              "Value": 100.0
            },
            {
              "Property": "Time_interval_max",
              "Value": 1000.0
            },
            {
              "Property": "Minimum_area_multiplier_raw",
              "Value": 50.0
            },
            {
              "Property": "Randomizer_dev_min_raw",
              "Value": 5.0
            },
            {
              "Property": "Randomizer_dev_max_raw",
              "Value": 10.0
            },
            {
              "Property": "Split_xy",
              "Value": null
            },
            {
              "Property": "Minimum_area_multiplier_x_raw",
              "Value": 50.0
            },
            {
              "Property": "Minimum_area_multiplier_y_raw",
              "Value": 50.0
            }
          ],
          "Enable": false
        },
        {
          "Path": "RadialFollow.RadialFollowSmoothingTabletSpace",
          "Settings": [
            {
              "Property": "OuterRadius",
              "Value": 1.0
            },
            {
              "Property": "InnerRadius",
              "Value": 0.0
            },
            {
              "Property": "SmoothingCoefficient",
              "Value": 0.95
            },
            {
              "Property": "SoftKneeScale",
              "Value": 1.0
            },
            {
              "Property": "SmoothingLeakCoefficient",
              "Value": 0.0
            }
          ],
          "Enable": false
        },
        {
          "Path": "RadialFollow.RadialFollowSmoothingScreenSpace",
          "Settings": [
            {
              "Property": "OuterRadius",
              "Value": 5.0
            },
            {
              "Property": "InnerRadius",
              "Value": 0.0
            },
            {
              "Property": "SmoothingCoefficient",
              "Value": 0.95
            },
            {
              "Property": "SoftKneeScale",
              "Value": 1.0
            },
            {
              "Property": "SmoothingLeakCoefficient",
              "Value": 0.0
            }
          ],
          "Enable": false
        }
      ],
      "Bindings": {
        "TipActivationThreshold": 0.0,
        "TipButton": {
          "Path": "OpenTabletDriver.Desktop.Binding.MouseBinding",
          "Settings": [
            {
              "Property": "Button",
              "Value": "Left"
            }
          ],
          "Enable": true
        },
        "EraserActivationThreshold": 0.0,
        "EraserButton": null,
        "PenButtons": [
          {
            "Path": "OpenTabletDriver.Desktop.Binding.MouseBinding",
            "Settings": [
              {
                "Property": "Button",
                "Value": "Right"
              }
            ],
            "Enable": true
          },
          {
            "Path": "OpenTabletDriver.Desktop.Binding.MouseBinding",
            "Settings": [
              {
                "Property": "Button",
                "Value": "Middle"
              }
            ],
            "Enable": true
          }
        ],
        "AuxButtons": [],
        "MouseButtons": [],
        "MouseScrollUp": null,
        "MouseScrollDown": null
      }
    }
  ],
  "Tools": []
}
```

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by solonovamax** [comment]
I know the issue isn't very informative, but I don't have a lot to work on

it just always crashes when I run the `otd` command. (also the systemd script crashes as well, but that just runs `odt`, I assume)

**Comment by X9VoiD** [comment]
Reset settings, you're using 0.7.x settings on a 0.6.x daemon. They have incompatible settings format.

**Comment by solonovamax** [comment]
will do, ty

**Comment by solonovamax** [comment]
not sure if you're the maintainer of it or not, but the aur package for `opentabletdriver` seems to be packaging 0.6.0.4

**Comment by X9VoiD** [comment]
Already known, just wait till maintainers update the package.
