### ISSUE TITLE
UX crash on startup when mode is not absolute mode

### ISSUE THREAD

**Issue by user202729** [OpenTabletDriver/OpenTabletDriver#2855]
### Steps to Reproduce

 1. Set mode to "Relative Mode", save the changes.
 2. Exit the UX and reopen it.

### Expected Behavior

It opens normally.

### Observed Behavior

 See the error

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTabletDriver.UX.Controls.DigitizerPanel.<>c__DisplayClass0_1.<.ctor>b__1(Object <p0>, EventArgs <p1>) in /home/user202729/OpenTabletDriver/OpenTabletDriver.UX/Controls/DigitizerPanel.cs:line 36
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.ListControl.OnSelectedKeyChanged(EventArgs e)
   at Eto.Forms.ListControl.OnSelectedIndexChanged(EventArgs e)
   at Eto.Forms.ListControl.Callback.OnSelectedIndexChanged(ListControl widget, EventArgs e)
   at Eto.GtkSharp.Forms.Controls.DropDownHandler`3.DropDownConnector.HandleChanged(Object sender, EventArgs e)
   at InvokeStub_EventHandler.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

The error was mentioned as a part of #2441 .

### Tablet Device

10moon 1060N

### Diagnostic Information

Remark: The problem is the line

```
                    if (editorPanel.Content.ID == profile.OutputMode.Path)
                        return;
```

where `editorPanel.Content == null`.If I edit it as follows, the problem no longer happen:

```
                    if (editorPanel.Content != null && editorPanel.Content.ID == profile.OutputMode.Path)
```

nevertheless, I'm not really following the logic of the code, because `editorPanel` has just been created earlier then the `Content` should always be `null`? In that case the whole check can just be removed?

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
Is this current master? This should fall under #2441, and will be fixed in #2772.
