### ISSUE TITLE
Console application (otd) should notify of daemon connection early on launch

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#2898]
### Description

There is confusion among users in the move from `otd` to `otd-daemon` - we should probably have some sort of message notifying the user that `otd-daemon` is the way to start the daemon.

---

Current behavior is to do nothing but time out after 5 seconds, in which case an exception stack trace is thrown:
```
$ otd
Unhandled exception. System.TimeoutException: Connecting to daemon failed after 5 seconds.
   at OpenTabletDriver.Desktop.RPC.RpcClient`1.Connect() in /home/gonx/.cache/paru/clone/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Desktop/RPC/RpcClient.cs:line 35
   at OpenTabletDriver.Console.ApplicationLifetime.Run(String[] args) in /home/gonx/.cache/paru/clone/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Console/ApplicationLifetime.cs:line 24
   at OpenTabletDriver.Console.Program.Main(String[] args) in /home/gonx/.cache/paru/clone/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.Console/Program.cs:line 11
   at OpenTabletDriver.Console.Program.<Main>(String[] args)
/usr/bin/otd: line 3: 17316 Aborted                 (core dumped) /usr/lib/opentabletdriver/OpenTabletDriver.Console "$@"
```

---

Proposed behavior would be:
Initial message:
```
$ otd
Connecting to the OpenTabletDriver daemon... (start 'otd-daemon' if you haven't)
```
Once connection completes:
```
$ otd
Connecting to the OpenTabletDriver daemon... (start 'otd-daemon' if you haven't)
Connected!
<default output text of `otd`>
```

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment]
adding onto this 0.6.x doesn't even timeout, will just sit indefinitely until the daemon is started.
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/22662856/c11c5d65-4632-4491-9015-13ba97c4611d)
