### ISSUE TITLE
No method by the name 'GetTablets' is found

### ISSUE THREAD

**Issue by xenzer** [OpenTabletDriver/OpenTabletDriver#2915]
### Steps to Reproduce

i have no idea, but when i open the app it immediately gives me all these errors

### Expected Behavior

the app to open

### Observed Behavior

the app gives errors

### Tablet Device

Huion HS64

### Diagnostic Information

StreamJsonRpc.RemoteMethodNotFoundException: No method by the name 'GetTablets' is found.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at OpenTabletDriver.UX.Controls.Output.OutputModeEditor.<>c__DisplayClass1_0.<<UpdateTablet>b__0>d.MoveNext() in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Controls\Output\OutputModeEditor.cs:line 49
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment]
Restart daemon or computer.
