### ISSUE TITLE
The process cannot access the file '.../tablet-data.txt' because it is being used by another process.

### ISSUE THREAD

**Issue by Willian-Zhang** [OpenTabletDriver/OpenTabletDriver#3078]
### Steps to Reproduce

1. force quit .app for hanging (unknown reason)
2. start up .app again

### Expected Behavior

tablet shown connected

### Observed Behavior

tablet not detected 

### Tablet Device

PTH-450

### Diagnostic Information

```
System.IO.IOException: The process cannot access the file '/Users/<omiited>/Library/Application Support/OpenTabletDriver/tablet-data.txt' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenWrite(String path)
   at OpenTabletDriver.UX.Windows.Tablet.TabletDebugger..ctor() in /home/runner/work/OpenTabletDriver/OpenTabletDriver/OpenTabletDriver.UX/Windows/Tablet/TabletDebugger.cs:line 164
   at System.RuntimeType.CreateInstanceOfT()
```

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by gonX** [comment]
Fixed in #3988. The fix will be included in the release following 0.6.5.1
