### ISSUE TITLE
Cannot get diagnostic information on Fedora 39

### ISSUE THREAD

**Issue by azuredusk10** [OpenTabletDriver/OpenTabletDriver#3195]
### Steps to Reproduce

1. Go to Help > Export Diagnostics
2. See error message.

I've been able to reproduce this regardless of whether a tablet is plugged in or not, and regardless of whether it's a supported tablet or not.

My system information: 
Hardware Information:
Hardware Model:                              Framework Laptop 12th Gen Intel Core
Memory:                                      32.0 GiB
Processor:                                   12th Gen Intel® Core™ i5-1240P × 16
Graphics:                                    Intel® Graphics (ADL GT2)
Disk Capacity:                               1.0 TB

Software Information:
Firmware Version:                            03.05
OS Name:                                     Fedora Linux 39 (Workstation Edition)
OS Build:                                    (null)
OS Type:                                     64-bit
GNOME Version:                               45.3
Windowing System:                            Wayland
Kernel Version:                              Linux 6.6.13-200.fc39.x86_64

### Expected Behavior

Be given the option to export the diagnostic information

### Observed Behavior

I get an error message that says
"An application error has occured. Report this to the developers!"

```
StreamJsonRpc.RemoteSerializationException: Error writing JSON RPC Message: FormatException: Input string was not in a correct format.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at OpenTabletDriver.UX.MainForm.ExportDiagnostics() in /__w/OpenTabletDriver/OpenTabletDriver/dist/redhat/opentabletdriver/BUILD/opentabletdriver-0.6.4.0/OpenTabletDriver.UX/MainForm.cs:line 642
```

In the console, a new row is added, with the group name "RemoteSerializationException"

### Tablet Device

XP-PEN Deco Pro (Gen 2) XLW, and Wacom Intuos Pro M

### Diagnostic Information

No diagnostic information was generated

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by fybx** [comment]
Same error occurs both on Manjaro Linux and Arch Linux with kernels 6.5 and 6.7, X11 and Wayland.

**Comment by jamesbt365** [comment]
Is this still an issue on the latest release of the driver, I have not seen this problem in long enough that I think its no longer an issue.

I couldn't reproduce it to begin with, so I can't test this myself.

**Comment by gonX** [comment]
Based on the stack trace this looks like it's failing when asking Daemon to return the list of devices:
https://github.com/OpenTabletDriver/OpenTabletDriver/blob/9f4e357910a5917ef86166c195c858c1c65b46d2/OpenTabletDriver.UX/MainForm.cs#L642

Not sure how this fails, it returns `SerializedDeviceEndpoint` which has both an empty and an `IDeviceEndpoint` constructor. Stretch guess: maybe the `int`s in the interface need to be set as nullable?

**Comment by gonX** [comment]
Thanks for the report @azuredusk10, but we are sadly still seeing reports of this bug on our Discord server.
