### ISSUE TITLE
I can do testing to add support for the XP-Pen Artist 13.3 Pro's Wheel

### ISSUE THREAD

**Issue by Nukley** [OpenTabletDriver/OpenTabletDriver#3300]
### Description

I have an Artist 13.3 Pro tablet, I have found this driver to be useful for drawing in the past, however once I got a new tablet, one thing started to bug me... The wheel is not supported! I actually did look in the tablet debugger and found the specific value that is changing.

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/26724236/e79a0039-7215-464b-9702-b115fe7d3618)
This value changes to 1 if rotating clockwise, constantly going between 1 and 0, 0 between each tick, and 1 meaning it got an input. This is very brief and I had to stare at it for a while to see.

Same deal for counterclockwise, except instead of 1 and 0, it's 2 and 0.

Let me know if you need any more information or anything else from me! Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [x] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
OTD doesn't support any wheels at all right now, it simply is missing the infrastructure to handle them. Lets keep things clean and keep everything in one issue. See #1367

**Comment by jamesbt365** [comment]
OTD doesn't support any wheels at all right now, it simply is missing the infrastructure to handle them. Lets keep things clean and keep everything in one issue. See #1367

**Comment by gonX** [comment]
Wheel support is now available in our infrastructure in `0.6.x`. Feel free to implement this in the parser if it isn't automatically present.

**Comment by gonX** [comment]
You need to provide a data recording containing only the following 2 movements:

- 2 full clockwise circles
- 2 full counterclockwise circles

(the circles don't need to be perfect)

If they're sliders ("bars") you can do 2 full swipes in both directions instead.

You can record the raw data by opening the OpenTabletDriver interface, and then going to Tablets -> Tablet Debugger. There will then be a "Enable Data Recording" checkbox on the right hand of the new window. Then a `tablet-data`  file will be available in your [app data](https://opentabletdriver.net/Wiki/FAQ/General#appdata) folder.

**Comment by gonX** [comment]
Whoops, I thought I had another issue open, so the above message is incorrect for this issue. The wheel support for this tablet should be added by #4641, please test it.

**Comment by Nukley** [comment]
> Whoops, I thought I had another issue open, so the above message is incorrect for this issue. The wheel support for this tablet should be added by [#4641](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/4641), please test it.

Compiled it and can confirm that it does work, but only in Absolute mode. In Artist mode it causes the daemon to have a hiccup and I need to make the UX manually reattach to it.

```
[InvalidOperationException:Error]       Pointer was not injected by daemon
   at OpenTabletDriver.Desktop.Binding.MouseScrollBinding.Scroll() in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/MouseScrollBinding.cs:line 96
   at OpenTabletDriver.Desktop.Binding.MouseScrollBinding.Press(TabletReference tablet, IDeviceReport report) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/MouseScrollBinding.cs:line 84
   at OpenTabletDriver.Desktop.Binding.DeltaThresholdBindingState.Invoke(TabletReference tablet, IDeviceReport report, Double delta) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/DeltaThresholdBindingState.cs:line 27
   at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleRelativeWheelReport(TabletReference tabletReference, IRelativeWheelReport relativeWheelReport) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/BindingHandler.cs:line 79
   at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleBinding(IDeviceReport report) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/BindingHandler.cs:line 65
   at OpenTabletDriver.Plugin.Output.OutputMode.Read(IDeviceReport deviceReport) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Plugin/Output/OutputMode.cs:line 120
   at OpenTabletDriver.InputDeviceTree.HandleReport(Object sender, IDeviceReport report) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver/InputDeviceTree.cs:line 61
   at OpenTabletDriver.Devices.DeviceReader`1.Main() in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver/Devices/DeviceReader.cs:line 111
```

It might be noteworthy that within the 2 years of opening this issue, I have obtained a much better computer, and am now running KDE under Wayland as opposed to X11 like I was before. I am experiencing additional issues with opentabletdriver such as improper pen-to-screen mapping in artist mode, which I am unsure are caused by it or wayland, however the extent of that might be more worthy of it's own issue. Point of mentioning all this being, I'm not sure if the error is caused by my new setup, or opentabletdriver itself.

**Comment by gonX** [comment]
> > Whoops, I thought I had another issue open, so the above message is incorrect for this issue. The wheel support for this tablet should be added by [#4641](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/4641), please test it.
> 
> Compiled it and can confirm that it does work, but only in Absolute mode. In Artist mode it causes the daemon to have a hiccup and I need to make the UX manually reattach to it.
> 
> ```
> [InvalidOperationException:Error]       Pointer was not injected by daemon
>    at OpenTabletDriver.Desktop.Binding.MouseScrollBinding.Scroll() in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/MouseScrollBinding.cs:line 96
>    at OpenTabletDriver.Desktop.Binding.MouseScrollBinding.Press(TabletReference tablet, IDeviceReport report) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/MouseScrollBinding.cs:line 84
>    at OpenTabletDriver.Desktop.Binding.DeltaThresholdBindingState.Invoke(TabletReference tablet, IDeviceReport report, Double delta) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/DeltaThresholdBindingState.cs:line 27
>    at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleRelativeWheelReport(TabletReference tabletReference, IRelativeWheelReport relativeWheelReport) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/BindingHandler.cs:line 79
>    at OpenTabletDriver.Desktop.Binding.BindingHandler.HandleBinding(IDeviceReport report) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Desktop/Binding/BindingHandler.cs:line 65
>    at OpenTabletDriver.Plugin.Output.OutputMode.Read(IDeviceReport deviceReport) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver.Plugin/Output/OutputMode.cs:line 120
>    at OpenTabletDriver.InputDeviceTree.HandleReport(Object sender, IDeviceReport report) in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver/InputDeviceTree.cs:line 61
>    at OpenTabletDriver.Devices.DeviceReader`1.Main() in /home/red/Downloads/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver-06x-xppen-artist13.3pro-add-wheel-spec/OpenTabletDriver/Devices/DeviceReader.cs:line 111
> ```
> 
> It might be noteworthy that within the 2 years of opening this issue, I have obtained a much better computer, and am now running KDE under Wayland as opposed to X11 like I was before. I am experiencing additional issues with opentabletdriver such as improper pen-to-screen mapping in artist mode, which I am unsure are caused by it or wayland, however the extent of that might be more worthy of it's own issue. Point of mentioning all this being, I'm not sure if the error is caused by my new setup, or opentabletdriver itself.

It looks like you're having 2 issues at once:

- Using an unsupported binding for the output mode, tracked in #2078 
  - Mouse buttons do not work in Artist Mode, though the error has been changed to break the pipeline to avoid confusion
- The mapping is also being handled by your desktop environment. Change its tablet mapping to map to all monitors/screens.
