### ISSUE TITLE
Support Request: Не работают плагины/при скачивании любого плагина программа выдаёт ошибку 

### ISSUE THREAD

**Issue by ruvin86** [OpenTabletDriver/OpenTabletDriver#3495]
### What do you need help with?

OpenTabletDriver при заходе в Plugin Manager, затем выбрав к примеру "DevocubFiltres", через некоторое время после начала установки программа выдаёт ошибку. После закрытия ошибки выдаёт "Lost connection to deamon, exiting", ну и после нажатия ok программа вылетает
![1](https://github.com/user-attachments/assets/48e5fea1-c65c-4c43-a714-9d0798975143)

![2](https://github.com/user-attachments/assets/60344d48-e1c8-49d1-a108-1e4e42689407)

### What have you tried?

Пробовал перезапустить пк после установки, переустановить программу, также открывал программу на разных дисках.
P.S. открываю не от имени администратора 
Нашёл похожую проблему у этого запроса, но там не нашёл решения: https://github.com/opentabletdriver/opentabletdriver/issues/2789

### Diagnostic Information

[11.json](https://github.com/user-attachments/files/17436494/11.json)

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync(JsonRpcRequest request, Type expectedResultType, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at OpenTabletDriver.UX.Windows.Plugins.PluginManagerWindow.DownloadAndInstall(PluginMetadata metadata) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Windows\Plugins\PluginManagerWindow.cs:line 83
   at OpenTabletDriver.UX.Windows.Plugins.MetadataViewer.InstallHandler(Object sender, EventArgs e) in D:\a\OpenTabletDriver\OpenTabletDriver\OpenTabletDriver.UX\Windows\Plugins\MetadataViewer.cs:line 226
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   P.S. этот код ошибка выдала после неудачной установки. А кода после которого программа закрывается нету, т.к. не могу скопировать чисто физически.
   
 
![3](https://github.com/user-attachments/assets/e52788ea-00ce-4099-aee0-aca5a7655e79)

![4](https://github.com/user-attachments/assets/5ab54527-2fb4-4532-965b-3dae536016c4)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by ruvin86** [comment]
Спасибо помогло!
