### ISSUE TITLE
GUI frontend on Linux looks broken

### ISSUE THREAD

**Issue by ZnCookie** [OpenTabletDriver/OpenTabletDriver#3532]
### Steps to Reproduce

1.Open otd-gui

2.Prompt "Application Error"
```
StreamJsonRpc.RemoteSerializationException: 写入 JSON RPC 消息时出错: JsonSerializationException: Self referencing loop detected with type 'OpenTabletDriver.Desktop.Interop.Display.Display'. Path ''.

   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at OpenTabletDriver.UX.App.Synchronize() in /build/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.UX/App.cs:line 192
   at OpenTabletDriver.UX.MainForm.OnConnected() in /build/opentabletdriver-git/src/OpenTabletDriver/OpenTabletDriver.UX/MainForm.cs:line 163
```

### Expected Behavior

Open the GUI frontend

### Observed Behavior

The driver seems to be working fine, but the GUI front end is broken
```
zncookie@Colorful-PC ~/Desktop> systemctl status --user opentabletdriver
* opentabletdriver.service - OpenTabletDriver Daemon
     Loaded: loaded (/usr/lib/systemd/user/opentabletdriver.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-11-19 18:40:53 CST; 20min ago
 Invocation: 060cae93eac64e8494d926749f6c0c27
   Main PID: 1418 (sh)
      Tasks: 20 (limit: 18649)
     Memory: 126M (peak: 136.5M)
        CPU: 2.688s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/opentabletdriver.service
             |-1418 sh /usr/bin/otd-daemon
             `-1425 /usr/lib/opentabletdriver/OpenTabletDriver.Daemon

Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [LinuxArtistMode:Debug]        Input: [152x95@<76, 47.5>:0<C2><B0>]
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [LinuxArtistMode:Debug]        Output: [1920x1080@<960, 540>]
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [LinuxArtistMode:Debug]        LockAspectRatio: False
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [LinuxArtistMode:Debug]        AreaClipping: True
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [LinuxArtistMode:Debug]        AreaLimiting: True
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [LinuxArtistMode:Debug]        LockToBounds: True
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [Wacom CTL-472:Info]        Output mode: Artist Mode
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [MouseBinding:Debug]        Button: Left
Nov 19 18:53:15 Colorful-PC otd-daemon[1425]: [Settings:Info]        Driver is enabled.
Nov 19 18:57:33 Colorful-PC otd-daemon[1425]: [IPC:Debug]        Connected to a client.
```

### Tablet Device

Wacom CTL-472

### Diagnostic Information

I can't do it, it prompts the same error

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
It is not recommended to use a git build of the driver, it is seriously unstable at this time as it is on an almost completely rewritten codebase that still needs work.

See: #2595, #2594, #2573, #2544, #2484, #2441, #2409, #2408 and potentially more.

Remove ~/.config/OpenTabletDriver and install the latest stable build instead.
